#! /bin/bash -x

sudo yum install -y java-1.8.0-openjdk-devel || exit $?

MAVEN_VERSION=3.5.4

if ! [ -d $HOME/sys/apache-maven-$MAVEN_VERSION ]; then
    mkdir -p $HOME/sys || exit $?
    pushd $HOME/sys || exit $?
    wget -q -O apache-maven-$MAVEN_VERSION-bin.tar.gz http://apache.claz.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz || exit $?
    tar -xzf apache-maven-$MAVEN_VERSION-bin.tar.gz
    sed -i '1i PATH=$HOME/sys/apache-maven-'$MAVEN_VERSION'/bin:$PATH' $HOME/.bashrc
    PATH=$HOME/sys/apache-maven-$MAVEN_VERSION/bin:$PATH
    popd
fi

if ! [ -d $HOME/sys/node-v8.10.0-linux-x64 ]; then
    mkdir -p $HOME/sys || exit $?
    pushd $HOME/sys || exit $?
    wget -q -O node-v8.10.0-linux-x64.tar.xz https://nodejs.org/dist/v8.10.0/node-v8.10.0-linux-x64.tar.xz || exit $?
    tar -xJf node-v8.10.0-linux-x64.tar.xz || exit $?
    sed -i '1i PATH=$PATH:$HOME/sys/node-v8.10.0-linux-x64/bin' $HOME/.bashrc
    PATH=$PATH:$HOME/sys/node-v8.10.0-linux-x64/bin
    popd
fi

if ! npm list -g @angular/cli > /dev/null 2>&1; then
    npm install -g @angular/cli || exit $?
fi
